### ISSUE TITLE
Legendre function is broken

### ISSUE THREAD

**Issue by JASory** [cmpute/num-modular#1]
a^p-1 = 1 mod p  is a necessary but not sufficient condition for primality. This is resulting in an extremely high error rate.

**Comment by cmpute** [comment]
I intentionally didn't include the primality check in the legendre function, because this crate doesn't deal with anything with primality test. This is clearly stated in the documentation

**Comment by JASory** [comment]
> I intentionally didn't include the primality check in the legendre function, because this crate doesn't deal with anything with primality test. This is clearly stated in the documentation

https://docs.rs/num-modular/0.5.1/num_modular/trait.ModularSymbols.html#tymethod.checked_legendre

**Comment by cmpute** [comment]
@JASory The doc says

> Checked version of [legendre()](https://docs.rs/num-modular/0.5.1/num_modular/trait.ModularSymbols.html#method.legendre), return [None](https://doc.rust-lang.org/nightly/core/option/enum.Option.html#variant.None) if n is not prime

This doesn't mean that it will do a full primality check (you can check the implementation). But the doc definitely needs to be improved, thanks for pointing out and I will make this clear
