### ISSUE TITLE
Please consider publishing version 0.6.0 on crates.io

### ISSUE THREAD

**Issue by triska** [cmpute/num-modular#4]
While getting Scryer Prolog to compile on 32-bit systems thanks to impressive recent work by @rujialiu, we noticed that 0.6.0 is not yet published on crates.io, so we had to use 0.5.2 as a fallback (0.5.1 fails to compile on 32-bit systems).

Could you please consider publishing the current version 0.6.0 on crates.io, and update `num-order` to use it?

For reference, here is the pertaining discussion in Scryer Prolog:

https://github.com/mthom/scryer-prolog/pull/1880#issuecomment-1694192681

Thank you a lot!

**Comment by rujialiu** [comment]
I don't have a compiler now but I can remember that the compile error with 32-bit system (in particular, I was trying `i686-pc-windows-msvc`) is because `divmod` is not found for something in `prim.rs`. If you think current 0.6.0 is not mature enough you can also make a 0.5.2 branch (so that `num-order` will use 0.5.2 automatically) with just that change. Thank you very much!

**Comment by cmpute** [comment]
I will work on a published version soon. The release of the new version is held by the development progress of `dashu`, but I will try to cut the new features and make a new release.

**Comment by cmpute** [comment]
> I don't have a compiler now but I can remember that the compile error with 32-bit system (in particular, I was trying `i686-pc-windows-msvc`) is because `divmod` is not found for something in `prim.rs`. If you think current 0.6.0 is not mature enough you can also make a 0.5.2 branch (so that `num-order` will use 0.5.2 automatically) with just that change. Thank you very much!

Could you please test the latest code again on `i686-pc-windows-msvc`? My CI tests on 32-bit Linux doesn't report any errors. I can release a new version after no other issues are found.

**Comment by rujialiu** [comment]
I can confirm the latest code works on `i686-pc-windows-msvc`, thanks!

**Comment by cmpute** [comment]
Thanks for confirming. I have published the version 0.6.0, including some break changes. Feel free to let me know if you want some assistance on adapting to the break changes.
